language: php

php:
  - 5.6
  - 7.0

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.0

before_script:
  - composer install --no-interaction --dev --prefer-dist

script:
  - vendor/bin/phpunit

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

branches:
  only:
    - master

